#! /bin/sh

battery_level="$(cat /sys/class/power_supply/BAT0/capacity)"
battery_health="$(cat /sys/class/power_supply/BAT0/capacity_level)"
battery_stage="$(cat /sys/class/power_supply/BAT0/status)"
cycle_count="$(cat /sys/class/power_supply/BAT0/cycle_count)"
battery_basic() {
	emo && echo -e "$batsym$battery_level% "
}
emo() {
	[ "$battery_stage" == "Discharging" ] && batsym="🔋" || batsym="🔌"
}
battery_detail() {
	echo -e "battery_level:$battery_level\t $battery_stage \ncycle_count:$cycle_count\nhealth: $battery_health\n"
}
case "$1" in
	-all ) battery_detail ;;
	-a ) battery_detail ;;
	"$NULL" ) battery_basic ;;
esac
