#! /bin/sh

check() {
	echo -e "$(date "+%e")\n$(curl -X GET "https://disease.sh/v3/covid-19/countries/Poland")" > ~/.cache/covid-19
}
short() {
	printf "TODAY 😷$( sed -n 2p ~/.cache/covid-19 | sed 's/"todayCases"//g'| cut -d ',' -f  10 ) 😀$(sed -n 2p ~/.cache/covid-19 | sed 's/"todayRecovered"//g' | cut -d ',' -f 14 ) \n"
}
list() {
	printf "TOTAL CASES$( sed -n 2p ~/.cache/covid-19 | sed 's/"cases"//g'| cut -d ',' -f 9) \n"
	printf "ACTIVE CASES$( sed -n 2p ~/.cache/covid-19 | sed 's/"active"//g'| cut -d ',' -f 15) ⚕\n"
}
update() {
	kill -36 $(pidof dwmblocks)
	notify-send "covid has been updated" && exit
}
man() {
	printf "\033[1mUSAGE : corona [option]\n\033[0;33m -a\tall data\n -h\thelp\n -u\tupdate\n NULL\tshort info\n" && exit
}
case "$1" in
	-a ) [ "$(date '+%e')" -eq "$(sed -n 1p ~/.cache/covid-19)" ] && list && short && exit || list && short && echo "Data are not up to date, try to update it [corona -u]" ;;
	-u ) [ "$(date '+%H')" -ge 12 ] && check || echo "There's no update available" && exit ;;
	-h ) man ;;
	"$NULL" ) [ "$(date '+%e')" -eq "$(sed -n 1p ~/.cache/covid-19)" ] && short && exit || echo "Data are not up to date, try to update it [corona -u]" && exit ;;
esac
