#!/bin/bash
brightnessctl || exit
brightness=$(brightnessctl g)
brightstatus() {
if [ $brightness -lt 32 ]; then
	echo $brightness "🌑 "
elif [ $brightness -lt 64 ]; then
	echo $brightness "🌙 "
elif [ $brightness -lt 128 ]; then
	echo $brightness "🌛 "
else
	echo $brightness "🌕 "
fi
}
case "$1" in
	-s ) brightnessctl s $2;;
	* ) brightstatus ;;
esac
