#! /bin/sh
# show your local IP.

case "$1" in
	-a ) ip -br addr show | grep UP | grep 192.168.1 ;;
	#-p ) ip -br addr show | grep UP | grep 192.168.1 | awk '{print $3}' ;;
	#-h ) echo "wifi-ip - show your local ip\n -p\t port information\n -a\t more detailed information\n" ;;
	* ) ip -br addr show | grep UP | grep 192.168.1 | awk '{print $3}' | sed 's/\/.*//' ;;
esac
